[package]
name = "binrw-test"
version = "0.0.1"
edition = "2021"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
strip = true
debug = false

[dependencies]
binrw = "0.14.1"
uuid = "1.11.0"